export enum News {
  SET_LATEST_NEWS = 'SET_LATEST_NEWS',
  SET_POPULAR_NEWS = 'SET_POPULAR_NEWS',
  GET_NEWS = 'GET_NEWS',
}

export enum Errors {
  SET_LATEST_NEWS_ERROR = 'SET_LATEST_NEWS_ERROR',
  SET_POPULAR_NEWS_ERROR = 'SET_POPULAR_NEWS_ERROR',
}
